LiberQRCode/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from qr import views

urlpatterns = [
    path('', include('qr.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qr/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include
from django.contrib.auth import views as auth_views
from qr import views


urlpatterns = [
    path('', views.index, name="index"),

    #QRCODES
    path('create_redirection/', views.create_redirection, name='create_redirection'),
    path('generate/', views.generate_qr_code, name='generate_qr_code'),
    path('myqrcodes/', views.my_qr_codes, name='my_qr_codes'),
    path('delete_qr_code/<int:qr_code_id>/', views.delete_qr_code, name='delete_qr_code'),
    path('redirection/<str:redirecting_link>/', views.redirect_to_original, name='redirect_to_original'),
    path('edit_qr_code/<int:qr_code_id>/', views.edit_qr_code, name='edit_qr_code'),

    #NORMAL LOGIN/REGISTER/LOGOUT
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    #DJANGO PASSWORD RESETING (not working)
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #PROFILE/EDIT PROFILE
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_edit'),
]

qr/models.py
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User
from django import forms


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=255)

    def __str__(self):
        return f"{self.user}"


class QRCode(models.Model):
    image = models.ImageField(upload_to='qrcodes/')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    original_link = models.URLField()
    redirect_link = models.CharField(unique=True, max_length=255)

    def __str__(self):
        return f"QR Code for: {self.original_link}"


class QRCodeEditForm(forms.ModelForm):
    class Meta:
        model = QRCode
        fields = ['original_link']


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

qr/views.py
import hashlib
from datetime import timezone
import random

from django.contrib import messages
from django.core.files import File
import qrcode
from io import BytesIO

from django.utils.text import slugify
from .models import QRCode, QRCodeEditForm, CustomUserCreationForm
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import UpdateView
from .models import Profile
from django.utils import timezone
from django.shortcuts import redirect
from social_django.utils import psa


def index(request):
    original_link = ""
    return render(request, 'index.html', {'original_link': original_link})


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def create_redirection(original_link):
    try:
        redirect_link = generate_unique_redirect(original_link)
        redirecting = QRCode.objects.get(redirect_link=redirect_link)
        redirect_link = create_redirection(original_link)
    except QRCode.DoesNotExist:
        pass
    return redirect_link


def generate_unique_redirect(original_link):
    unique_text = original_link + str(
        random.randint(1, 100000))
    unique_text_hash = hashlib.sha256(unique_text.encode()).hexdigest()

    slug = slugify(unique_text_hash)[:10]

    redirect_link = f"{slug}"

    return redirect_link


@login_required
def generate_qr_code(request):
    if request.method == "POST":
        original_link = request.POST.get('original_link', '')
        redirect_link = create_redirection(original_link)

        sanitized_text = slugify(original_link)
        qr_image = qrcode.make("https://qrcodeslibapp-7078f907bd77.herokuapp.com/redirection/" + redirect_link, box_size=15)
        qr_image_pil = qr_image.get_image()

        stream = BytesIO()
        qr_image_pil.save(stream, format='PNG')
        stream.seek(0)

        user_profile, created = Profile.objects.get_or_create(user=request.user)

        qr_code = QRCode(original_link=original_link, redirect_link=redirect_link, profile=user_profile)
        qr_code.save()
        qr_code.image.save(f'{sanitized_text}.png', File(stream))

        qr_code.created_at = timezone.now()
        qr_code.save()

        qr_codes = QRCode.objects.filter(profile=user_profile)

        return render(request, 'success.html', {'qr_codes': qr_codes, 'qr_code': qr_code, 'qr_text': original_link})


@login_required
def profile_view(request):
    user_profile, created = Profile.objects.get_or_create(user=request.user)
    return render(request, 'profile/profile.html', {'user_profile': user_profile})


class ProfileUpdateView(UpdateView):
    model = Profile
    fields = ['bio']
    template_name = 'profile/profile_edit.html'
    success_url = '/profile/'


@login_required
def my_qr_codes(request):
    user_profile, created = Profile.objects.get_or_create(user=request.user)
    qr_codes = QRCode.objects.filter(profile=user_profile)

    messages.get_messages(request)

    return render(request, 'myqrcodes/index.html', {'qr_codes': qr_codes})


def delete_qr_code(request, qr_code_id):
    if not request.user.is_authenticated:
        return redirect('login')

    qr_code = get_object_or_404(QRCode, id=qr_code_id)
    if qr_code.profile.user != request.user:
        return redirect('my_qr_codes')

    if request.method == 'POST':
        qr_code.delete()
    return redirect('my_qr_codes')


def edit_qr_code(request, qr_code_id):
    qr_code = get_object_or_404(QRCode, id=qr_code_id)

    if request.method == 'POST':
        form = QRCodeEditForm(request.POST, instance=qr_code)
        if form.is_valid():
            form.save()
            messages.success(request, 'QR code updated successfully')
            return redirect('my_qr_codes')
    else:
        form = QRCodeEditForm(instance=qr_code)

    return render(request, 'myqrcodes/edit_qr_code.html', {'form': form, 'qr_code': qr_code})


def redirect_to_original(request, redirecting_link):
    # Look up the Redirect object with the given redirecting_link
    redirect_object = get_object_or_404(QRCode, redirect_link=redirecting_link)

    original_link = redirect_object.original_link

    if not original_link.startswith("http://") and not original_link.startswith("https://"):
        original_link = "http://" + original_link

    return redirect(original_link)

qr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>QR Code Generator</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://www.dafontfree.net/embed/YmF1aGF1cy05My1yZWd1bGFyJmRhdGEvMTMvYi82NDQ3MS9CQVVIUzkzLlRURg" rel="stylesheet" type="text/css"/>
</head>
<style>
    body {
        padding-top: 70px;
    }
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
</style>
<body>
{% block navbar %}
    {% include 'menu.html' %}
{% endblock %}
{% block content %} {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

qr/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <style>
    body {
      background-color: #ffffff;
    }
    h2 {
        color: #113946;
        text-transform: uppercase;
        margin-top: 30px;
    }
    .container {
      background-color: #ffffff;
      color: #000000;
      border-radius: 30px;
      padding: 3em;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
    }

    .header {
      color: white;
      text-align: center;
      margin-top: 1em;
      margin-bottom: 1em;
      font-size: 34px;
      font-weight: bold;
    }

    .download-share-buttons {
      display: flex;
      justify-content: center;
      margin-top: 1em;
    }

    .download-share-buttons button {
      margin-right: 0.5em;
    }

    .py-2 {
      background-color: #2c2c2c;
    }
    .logo {
        width: 20%;
        margin: 0 auto;
    }
    .form-control {
        max-width: 60%;
        margin: 0 auto;
        border-radius: 50px;
    }
  </style>
<header class="header">
    <img src="/media/logo-header.png" alt="QRMotion logo" class="logo">
    <h2>Générateur de QRCodes dynamiques</h2>
  </header>
    <form method="post" action="{% url 'generate_qr_code' %}">
      {% csrf_token %}
      <h3><center>copiez votre lien pour générer un QRCode</center></h3>
      </br>
      <div class="input-group mb-3">
        <input type="text" class="form-control" aria-describedby="inputGroup-sizing-default" name="original_link" autofocus>


      </div>
      <div class="input-group mb-3">
        <input type="submit" style="max-width: 200px; margin: auto" class="form-control">
      </div>
    </form>
{% endblock %}

qr/templates/menu.html
<style>
    li a {
        color: #113946!important;
    }
    li a i {
        font-size: 24px;
        margin-left: 10px;
    }
    .right {
        position: absolute;
        right: 10px;
        width: 240px;
    }
    .profile-r {
        width: 110px;
        right: 120px;
    }
    .profile-r li {
        width: 100%!important;
    }
    .right li {
        width: 45%;
        display: inline-block;
    }
    .fixed-top {
        position: absolute!important;
    }
    #switch {
        display: none;
        position: fixed;
        top: 10px;
        left: 10px;
        z-index: 9999;
    }
    .logout {
        position: absolute;
        right: 10px;
    }
    #navbarNav {
      background-color: #EAD7BB!important;
    }
    .nav-link {
        display: flex;
        align-items: center;
        transition: all .3s;
    }
    .nav-link:hover {
        transform: scale(1.1);
    }
    .nav-link i {
        margin-right: 5px;
    }
    .nav-link img {
        margin-right: 5px;
    }
    .logo-xs {
        max-width: 24px;
    }
    .centerdiv {
        position: absolute;
        left: 50%;
        top: 10px;
        transform: translateX(-50%);
    }
    .centerdiv img {
        height: 40px;
    }
    @media only screen and (max-width: 600px) {
        body {
            padding-top: 0;
        }
        #switch {
            display: block;
        }
        #switch i {
            font-size: 24px;
            color: #113946;
        }
        #navbarNav {
            height: 100vh;
            position: fixed!important;
            display: none;
            padding: 0;
        }
        .navbar {
            height: 100vh;
        }
        .navbar ul {
            height: 100vh;
            padding-top: 50%;
        }
        .navbar ul li {
            width: 100%;
            text-align: center;
            margin-bottom: 50px;
            display: flex;
        justify-content: center;
        }
        .right {
            position: unset;
            margin: 0 auto;
        }
        .logout {
            position: unset;
        }
    }
</style>
<div class="toggleButton" id="switch">
    <i class="fa-solid fa-bars"></i>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top" id="navbarNav" style="width: 100%">
    <div class="navbar" style="width: 100%">
        <ul class="navbar-nav" style="width: 100%">
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><i class="fa-solid fa-house"></i> Accueil</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_qr_codes' %}"><img src="/media/logo-xs.png" alt="tiny qrcode logo" class="logo-xs"> My codes</a>
                </li>
                <li class="nav-item logout">
                    <a class="nav-link" href="{% url 'logout' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a>
                </li>
                <div class="right profile-r">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}"><i class="fa-solid fa-user"></i> Profile</a>
                    </li>
                </div>
                <div class="centerdiv">
                    <img src="/media/logo-big.png" alt="logo complet de QRMotion">
                </div>
            {% else %}
                <div class="right">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}"><i class="fa-solid fa-user-plus"></i> Signup</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
                    </li>
                </div>

            {% endif %}
        </ul>
    </div>
</nav>
<script>
    $(document).ready(function() {
        $("#switch").click(function() {
            $("#navbarNav").toggle();
        });
    });
</script>

qr/templates/myqrcodes/edit_qr_code.html
{% extends 'base.html' %}
{% block content %}
<!-- edit_qr_code.html -->
    <style>
        h2 {
            width: 100%;
            text-align: center;
            padding-top: 50px;
        }
        .formulaire {
            border: 1px solid darkgrey;
            margin: 0 auto;
            width: 50%;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            padding: 20px;
            border-radius: 15px;
        }
        #id_original_link {
            padding: 10px 5px;
            border: none;
            border-bottom: 1px solid darkgrey;
            width: 100%;
        }
        form {
            width: 100%;
        }
        .btn {
            background-color: black;
            color: white;
            transition: all .2s;
            margin: 0 5px;
        }
        .btn:hover {
            color: white;
            transform: scale(1.1);
        }
        .cancel-edit:hover {
            background-color: darkred;
        }
        .save-btn:hover {
            background-color: forestgreen;
        }
        .blackbar {
            position: fixed;
            top: 0;
            height: 50px;
            width: 100%;
            background-color: #2c2c2c;
        }
        @media only screen and (max-width: 600px) {
            .formulaire {
                width: 95%;
            }
        }
    </style>
    <div class="blackbar"></div>
    <h2>Edit QR Code</h2>
    <div class="formulaire">
        <form method="post" action="{% url 'edit_qr_code' qr_code.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="edit">
            {{ form.as_p }}
            <button type="submit" class="btn save-btn">Save Changes</button>
            <a href="{% url 'my_qr_codes' %}" class="cancel-edit btn">Cancel</a>
        </form>
    </div>
{% endblock %}

qr/templates/myqrcodes/index.html
{% extends 'base.html' %}
{% block content %}
    <style>
    h1 {
        width: 100%;
        text-align: center;
        text-transform: uppercase;
        font-size: 32px;
        margin-top: 30px;
    }
    .container {
        width: 75%;
        display: flex;
        justify-content: space-evenly;
        flex-wrap: wrap;
    }

    .qrcode {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        width: 320px;
        overflow-x: hidden;
        border: 1px solid darkgrey;
        border-radius: 15px;
        margin-bottom: 25px;
        transition: all .2s;
    }
    .qrcode:hover {
        box-shadow: rgba(0, 0, 0, 0.2) 0px 12px 28px 0px, rgba(0, 0, 0, 0.1) 0px 2px 4px 0px, rgba(255, 255, 255, 0.05) 0px 0px 0px 1px inset;
    }
    .code {
        border-radius: 15px;
        cursor: pointer;
    }
    .more {
        background-color: #EAD7BB;
        border-radius: 10px;
        color: #113946;
        display: block;
        height: 40px;
        line-height: 40px;
        text-decoration: none;
        padding: 0 15px;
        transition: all .3s;
        width: 300px;
        text-align: center;
        margin: 0 auto;
    }
    .more:hover {
        transform: scale(1.1);
        color: #113946;
    }
    .btn {
        color: #113946;
        text-decoration: none;
        padding: 5px 20px;
        border-radius: 10px;
        background-color: #EAD7BB;
        transition: all .2s;
        margin: 5px;
    }
    .btn:hover {
        transform: scale(1.1);
        color: white;
        font-weight: bold;
    }
    .delete-button:hover {
        background-color: #ce0000;
    }
    .save-button:hover {
        background-color: #009a08;
    }
    .btns {
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
    }
    .lien  {
        min-width: 100%;
        text-align: center;
    }

    /* Add your styles for the modal */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.9);
    }

    /* Style for the close button */
    .close {
        position: absolute;
        top: 80px;
        right: 30px;
        font-size: 30px;
        color: white;
        cursor: pointer;
    }

    /* Style for the modal image */
    #modalImage {
        display: block;
        margin: 0 auto;
        max-width: 80%;
        max-height: 80%;
    }

    /* Add more styles as needed for your modal */

    @media only screen and (max-width: 600px) {
        .container {
            width: 100%;
        }
        .blackbar {
            position: fixed;
            top: 0;
            height: 50px;
            width: 100%;
            background-color: #2c2c2c;
        }
        .modal {
            padding-top: 50%;
        }
        .close {
            top: 18%;
        }
    }
    </style>
    <div class="blackbar"></div>
    <h1>Mes QR Codes</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if qr_codes %}
        <div class="container">
            {% for qr_code in qr_codes %}
                <div class="qrcode">
                    <img src="{{ qr_code.image.url }}" alt="{{ qr_code.original_link }}" width="300" height="300" class="code">
                    <p class="lien">{{ qr_code.original_link }}</p>
                    <div class="btns">
                        <a href="{% url 'edit_qr_code' qr_code.id %}" class="edit-button btn"><i class="fa-solid fa-pen-to-square"></i></a>
                        <form method="post" action="{% url 'delete_qr_code' qr_code.id %}">
                            {% csrf_token %}
                            <button type="submit" name="action" value="delete" class="delete-button btn"><i class="fa-solid fa-trash"></i></button>
                        </form>
                        <a href="{{ qr_code.image.url }}" download="{{ qr_code.original_link }}.png" class="btn save-button"><i class="fa-solid fa-floppy-disk"></i></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No QR codes found for your profile.</p>
    {% endif %}
    <div id="qrModal" class="modal">
        <span class="close" id="closeModal">&times;</span>
        <img id="modalImage" src="" alt="QR Code">
    </div>

    <br>
    <a href="/" class="more">Créer un nouveau QR Code</a>
    <script>
        $(document).ready(function () {
            // Open the modal when a .qrcode div is clicked
            $('.code').on('click' , function () {
                // Get the QR code image source and original link
                var qrCodeImageSrc = $(this).attr('src');
                var originalLink = $(this).find('.lien').text();

                // Update the modal image and open the modal
                $('#modalImage').attr('src', qrCodeImageSrc);
                $('#qrModal').css('display', 'block');
            });

            // Close the modal when the close button is clicked
            $('#closeModal').on('click', function () {
                $('#qrModal').css('display', 'none');
            });
            $('#qrModal').on('click', function() {
                $(this).css('display', 'none');
            })
        });

    </script>
{% endblock %}

qr/templates/profile/profile.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .img_container {
            width: 150px;
            height: 150px;
            border-radius: 150px;
            overflow: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .img_container img {
            width: 150%;
        }

        textarea {
            height: 30px;
            border-radius: 15px;
        }

        h1 {
            width: 100%;
            text-align: center;
            margin-bottom: 30px;
        }

        .content {
            width: 75%;
            margin: 0 auto;
            margin-top: 10%;
            display: flex;
            justify-content: space-evenly;
            flex-wrap: wrap;
            border-radius: 25px;
            padding: 50px 0;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }
        .edit-profile {
            background-color: black;
            border-radius: 10px;
            color: white;
            height: 40px;
            line-height: 40px;
            text-decoration: none;
            padding: 0 15px;
            transition: all .3s;
        }
        .edit-profile:hover {
            transform: scale(1.1);
            color: white;
        }
    </style>
    <div class="content">
        <h1>profil de {{ user_profile.user.username }}</h1>
        <a href="{% url 'profile_edit' user_profile.pk %}" class="edit-profile">Edit Profile</a>
    </div>

{% endblock %}

qr/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .img_container {
            width: 150px;
            height: 150px;
            border-radius: 150px;
            overflow: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .img_container img {
            width: 150%;
        }
        textarea {
        height: 30px;
        border-radius: 15px;
    }
        h1 {
            width: 100%;
            text-align: center;
        }
        .content {
            width: 75%;
            margin: 0 auto;
            margin-top: 10%;
            display: flex;
            justify-content: space-evenly;
            border-radius: 25px;
            padding: 50px 0;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }
        .save-profile {
            background-color: black;
            border-radius: 10px;
            color: white;
            height: 40px;
            line-height: 40px;
            text-decoration: none;
            padding: 0 15px;
            transition: all .3s;
        }
        .save-profile:hover {
            transform: scale(1.1);
            color: white;
        }
    </style>
<h1>Edit Profile</h1>
    <div class="content">
        <form method="post" action="{% url 'profile_edit' profile.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save-profile">Save Changes</button>
        </form>
    </div>

{% endblock %}

qr/templates/success.html
{% extends 'base.html' %}
{% block content %}
<style>
        * {
            color: white;
            font-family: Verdana, sans-serif;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            background-color: #262626;
        }
        header {
            background-color: #646464;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            width: 100%;
            margin-bottom: 20px;
            padding: 20px;
        }
        h1 {
            width: 100%;
            text-align: center;
        }
        .img {
            display: flex;
            justify-content: center;
            margin-bottom: 50px;
        }
        img {
            border-radius: 15px;
            width: 200px;
        }
        .buttons {
            display: flex;
            justify-content: center;
            width: 100%;
        }
        .buttons a {
            background-color: white;
            border-radius: 5px;
            padding: 20px 10px;
            width: 250px;
            color: black;
            text-align: center;
            text-decoration: none;
            text-transform: uppercase;
            margin: 30px;
        }
        .list_img {
            width: 80%;
            display: flex;
            justify-content: space-evenly;
            flex-wrap: wrap;
            margin: 0 auto;
        }
        .imgdiv {
            width: 200px;
            text-align: center;
            margin-bottom: 20px;
        }
    </style>
    <header>
        <h1>QR Code Generated Successfully</h1>
        <p>The QR code for {{ qr_code.original_link }} has been generated and saved.</p>
    </header>
    <div class="img">
        <img src="{{ qr_code.image.url }}" alt="QR Code">
    </div>
    <div class="buttons">
        <a href="{{ qr_code.image.url }}" download="{{ qr_code.original_link }}.png">Download QR Code</a>
    </div>
{% endblock %}